package domain;

public enum Marca {
    TOYOTA, HONDA, FORD, CHEVROLET, BMW,
    MERCEDES_BENZ, AUDI, VOLKSWAGEN, HYUNDAI, KIA,
    NISSAN, PORSCHE, FERRARI, LAMBORGHINI, VOLVO,
    LAND_ROVER, SEAT, TESLA, PEUGEOT, RENAULT,
    YAMAHA, KAWASAKI, SUZUKI, HARLEY_DAVIDSON, DUCATI,
    VESPA, JEEP, FIAT, CITROEN, OPEL, MAZDA, LEXUS, 
    MITSUBISHI;
	
	public String getNombre() {
        return name();
    }

}
