package domain;

public enum Marca {
    TOYOTA, HONDA, FORD, CHEVROLET, BMW, MERCEDESBENZ, AUDI, VOLKSWAGEN, HYUNDAI, KIA, NISSAN, 
    LEXUS, MAZDA, SUBARU, PORSCHE, FERRARI, LAMBORGHINI, VOLVO, LANDROVER, SEAT, TESLA, PEUGEOT, 
    RENAULT, MITSUBISHI, FIAT, YAMAHA, KAWASAKI, SUZUKI
}
