package db;

import java.time.LocalDate;
import java.util.GregorianCalendar;

import domain.Cliente;
import domain.Coche;
import domain.Empleado;
import domain.Furgoneta;
import domain.Marca;
import domain.Moto;
import domain.TipoCajaCambios;
import domain.TipoCombustible;

public class DataBase {
	
	public static void cargarDatosPrueb() {
		DataBaseManager dbManager = new DataBaseManager();
		
		try {
			dbManager.conexion("resources/db/rebote.db");
			
			dbManager.eliminarTabla("cliente");
			dbManager.eliminarTabla("empleado");
			dbManager.eliminarTabla("coche");
			dbManager.eliminarTabla("furgoneta");
			dbManager.eliminarTabla("moto");
			dbManager.eliminarTabla("alquiler");
			dbManager.eliminarTabla("factura");
			
			dbManager.conexion("resources/db/rebote.db");
			
			Empleado empleado1 = new Empleado("Alberto", "García", "Ruiz", "12345678A", LocalDate.of(1983, 7, 12), "alberto.garcia@gmail.com", "alberto123", "ventas", 1450);
			Empleado empleado2 = new Empleado("María", "Fernández", "Lopez", "87654321B", LocalDate.of(1990, 1, 25), "maria.fernandez@gmail.com", "maria456", "marketing", 1600);
			Empleado empleado3 = new Empleado("Juan", "Martínez", "Sánchez", "23456789C", LocalDate.of(1975, 5, 30), "juan.martinez@gmail.com", "juan789", "recursos humanos", 1800);
			Empleado empleado4 = new Empleado("Elena", "Gómez", "Hernández", "34567890D", LocalDate.of(1995, 9, 15), "elena.gomez@gmail.com", "elena101", "ventas", 2000);
			Empleado empleado5 = new Empleado("Pablo", "Díaz", "Pérez", "45678901E", LocalDate.of(2001, 4, 11), "pablo.diaz@gmail.com", "pablo202", "marketing", 1550);
			
			dbManager.almacenarEmpleado(empleado1);
			dbManager.almacenarEmpleado(empleado2);
			dbManager.almacenarEmpleado(empleado3);
			dbManager.almacenarEmpleado(empleado4);
			dbManager.almacenarEmpleado(empleado5);
				
			Cliente cliente1 = new Cliente("Paula", "Sánchez", "Rosa", "65983241H", LocalDate.of(1991, 4, 29), "paula.sanchez@gmail.com", "paula687", "15430698M");
			Cliente cliente2 = new Cliente("Carlos", "Martín", "Gómez", "74589632J", LocalDate.of(1985, 11, 15), "carlos.martin@gmail.com", "carlos321", "32165487N");
			Cliente cliente3 = new Cliente("Ana", "López", "Díaz", "85236974L", LocalDate.of(1993, 7, 10), "ana.lopez@gmail.com", "ana123", "98765432Q");
			Cliente cliente4 = new Cliente("Luis", "Pérez", "Fernández", "96385274K", LocalDate.of(1988, 3, 22), "luis.perez@gmail.com", "luis456", "12345678Z");
			Cliente cliente5 = new Cliente("Sofía", "Hernández", "Ruiz", "65478932M", LocalDate.of(1995, 9, 18), "sofia.hernandez@gmail.com", "sofia789", "87654321T");
			Cliente cliente6 = new Cliente("Miguel", "Jiménez", "Torres", "15975384P", LocalDate.of(1982, 1, 5), "miguel.jimenez@gmail.com", "miguel852", "56473829X");
			Cliente cliente7 = new Cliente("Laura", "García", "Castro", "25836974N", LocalDate.of(1990, 6, 12), "laura.garcia@gmail.com", "laura963", "98374562Y");
			Cliente cliente8 = new Cliente("David", "Moreno", "Martínez", "75395146Q", LocalDate.of(1996, 8, 30), "david.moreno@gmail.com", "david741", "39284756W");
			Cliente cliente9 = new Cliente("Lucía", "Rodríguez", "Serrano", "84629137R", LocalDate.of(1987, 2, 28), "lucia.rodriguez@gmail.com", "lucia159", "72584931U");
			Cliente cliente10 = new Cliente("Javier", "Alonso", "Gutiérrez", "47586932S", LocalDate.of(1994, 10, 19), "javier.alonso@gmail.com", "javier753", "18462739V");	
			
			dbManager.almacenarCliente(cliente1);
			dbManager.almacenarCliente(cliente2);
			dbManager.almacenarCliente(cliente3);
			dbManager.almacenarCliente(cliente4);
			dbManager.almacenarCliente(cliente5);
			dbManager.almacenarCliente(cliente6);
			dbManager.almacenarCliente(cliente7);
			dbManager.almacenarCliente(cliente8);
			dbManager.almacenarCliente(cliente9);
			dbManager.almacenarCliente(cliente10);

			Coche coche1 = new Coche("1234BCD", Marca.AUDI, "A3", 25, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 5, 5);
			Coche coche2 = new Coche("5678EFG", Marca.AUDI, "Q7", 60, TipoCombustible.DIESEL, TipoCajaCambios.AUTOMATICO, 7, 5);
			Coche coche3 = new Coche("9101HIJ", Marca.AUDI, "A4", 35, TipoCombustible.HIBRIDO, TipoCajaCambios.MANUAL, 5, 4);
			Coche coche4 = new Coche("1122JKL", Marca.TOYOTA, "Corolla", 20, TipoCombustible.HIBRIDO, TipoCajaCambios.AUTOMATICO, 5, 4);
			Coche coche5 = new Coche("3344MNO", Marca.TOYOTA, "Camry", 30, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 5, 4);
			Coche coche6 = new Coche("5566PQR", Marca.TOYOTA, "RAV4", 40, TipoCombustible.HIBRIDO, TipoCajaCambios.AUTOMATICO, 5, 5);
			Coche coche7 = new Coche("7788STU", Marca.HONDA, "Civic", 18, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 5, 4);
			Coche coche8 = new Coche("9900VWX", Marca.HONDA, "CR-V", 30, TipoCombustible.DIESEL, TipoCajaCambios.AUTOMATICO, 5, 5);
			Coche coche9 = new Coche("1022YZA", Marca.HONDA, "Accord", 25, TipoCombustible.HIBRIDO, TipoCajaCambios.MANUAL, 5, 4);
			Coche coche10 = new Coche("1234ABC", Marca.FORD, "Focus", 18, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 5, 5);
			Coche coche11 = new Coche("5678DEF", Marca.FORD, "Fiesta", 12, TipoCombustible.GASOLINA, TipoCajaCambios.AUTOMATICO, 5, 3);
			Coche coche12 = new Coche("9101GHI", Marca.FORD, "Mustang", 50, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 4, 2);
			Coche coche13 = new Coche("1122JKL", Marca.CHEVROLET, "Cruze", 18, TipoCombustible.GASOLINA, TipoCajaCambios.AUTOMATICO, 5, 4);
			Coche coche14 = new Coche("3344MNO", Marca.CHEVROLET, "Malibu", 25, TipoCombustible.HIBRIDO, TipoCajaCambios.MANUAL, 5, 4);
			Coche coche15 = new Coche("5566PQR", Marca.CHEVROLET, "Traverse", 45, TipoCombustible.DIESEL, TipoCajaCambios.AUTOMATICO, 7, 5);
			Coche coche16 = new Coche("7788STU", Marca.BMW, "Serie 3", 40, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 5, 4);
			Coche coche17 = new Coche("9900VWX", Marca.BMW, "X5", 70, TipoCombustible.DIESEL, TipoCajaCambios.AUTOMATICO, 5, 5);
			Coche coche18 = new Coche("1022YZA", Marca.BMW, "Z4", 55, TipoCombustible.HIBRIDO, TipoCajaCambios.MANUAL, 2, 2);
			Coche coche19 = new Coche("1122JKL", Marca.MERCEDES_BENZ, "Clase A", 30, TipoCombustible.GASOLINA, TipoCajaCambios.AUTOMATICO, 5, 4);
			Coche coche20 = new Coche("3344MNO", Marca.MERCEDES_BENZ, "Clase C", 40, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 5, 4);
			Coche coche21 = new Coche("5566PQR", Marca.MERCEDES_BENZ, "GLC", 60, TipoCombustible.HIBRIDO, TipoCajaCambios.AUTOMATICO, 5, 5);
			Coche coche22 = new Coche("7788STU", Marca.AUDI, "A6", 45, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 5, 5);
			Coche coche23 = new Coche("9900VWX", Marca.AUDI, "Q5", 50, TipoCombustible.HIBRIDO, TipoCajaCambios.AUTOMATICO, 5, 5);
			Coche coche24 = new Coche("1022YZA", Marca.AUDI, "R8", 120, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 2, 2);
			Coche coche25 = new Coche("1234BCD", Marca.VOLKSWAGEN, "Golf", 22, TipoCombustible.HIBRIDO, TipoCajaCambios.AUTOMATICO, 5, 4);
			Coche coche26 = new Coche("5678EFG", Marca.VOLKSWAGEN, "Tiguan", 35, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 5, 5);
			Coche coche27 = new Coche("9101HIJ", Marca.VOLKSWAGEN, "Polo", 15, TipoCombustible.GASOLINA, TipoCajaCambios.AUTOMATICO, 5, 4);
			Coche coche28 = new Coche("1122JKL", Marca.HYUNDAI, "Elantra", 18, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 5, 4);
			Coche coche29 = new Coche("3344MNO", Marca.HYUNDAI, "Santa Fe", 35, TipoCombustible.HIBRIDO, TipoCajaCambios.AUTOMATICO, 5, 5);
			Coche coche30 = new Coche("5566PQR", Marca.HYUNDAI, "Kona", 25, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 5, 4);
			Coche coche31 = new Coche("7788STU", Marca.KIA, "Optima", 25, TipoCombustible.HIBRIDO, TipoCajaCambios.AUTOMATICO, 5, 4);
			Coche coche32 = new Coche("9900VWX", Marca.KIA, "Sportage", 30, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 5, 5);
			Coche coche33 = new Coche("1022YZA", Marca.KIA, "Seltos", 27, TipoCombustible.GASOLINA, TipoCajaCambios.AUTOMATICO, 5, 5);
			Coche coche34 = new Coche("1122JKL", Marca.NISSAN, "Altima", 25, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 5, 4);
			Coche coche35 = new Coche("3344MNO", Marca.NISSAN, "Leaf", 35, TipoCombustible.ELECTRICO, TipoCajaCambios.AUTOMATICO, 5, 5);
			Coche coche36 = new Coche("5566PQR", Marca.NISSAN, "X-Trail", 35, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 5, 5);
			Coche coche37 = new Coche("7788STU", Marca.PORSCHE, "911", 100, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 2, 2);
			Coche coche38 = new Coche("9900VWX", Marca.PORSCHE, "Macan", 60, TipoCombustible.DIESEL, TipoCajaCambios.AUTOMATICO, 5, 5);
			Coche coche39 = new Coche("1022YZA", Marca.PORSCHE, "Panamera", 90, TipoCombustible.HIBRIDO, TipoCajaCambios.MANUAL, 4, 4);
			Coche coche40 = new Coche("1122JKL", Marca.FERRARI, "488 GTB", 250, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 2, 2);
			Coche coche41 = new Coche("3344MNO", Marca.FERRARI, "Portofino", 250, TipoCombustible.GASOLINA, TipoCajaCambios.AUTOMATICO, 4, 2);
			Coche coche42 = new Coche("5566PQR", Marca.FERRARI, "Roma", 230, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 4, 2);
			Coche coche43 = new Coche("7788STU", Marca.LAMBORGHINI, "Huracán", 250, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 2, 2);
			Coche coche44 = new Coche("9900VWX", Marca.LAMBORGHINI, "Aventador", 350, TipoCombustible.GASOLINA, TipoCajaCambios.AUTOMATICO, 2, 2);
			Coche coche45 = new Coche("1022YZA", Marca.LAMBORGHINI, "Urus", 450, TipoCombustible.HIBRIDO, TipoCajaCambios.AUTOMATICO, 5, 5);
			Coche coche46 = new Coche("1122JKL", Marca.VOLVO, "XC60", 40, TipoCombustible.HIBRIDO, TipoCajaCambios.AUTOMATICO, 5, 5);
			Coche coche47 = new Coche("3344MNO", Marca.VOLVO, "S90", 55, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 5, 4);
			Coche coche48 = new Coche("5566PQR", Marca.VOLVO, "V90", 60, TipoCombustible.GASOLINA, TipoCajaCambios.AUTOMATICO, 5, 5);
			Coche coche49 = new Coche("7788STU", Marca.LAND_ROVER, "Defender", 70, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 5, 5);
			Coche coche50 = new Coche("9900VWX", Marca.LAND_ROVER, "Range Rover", 90, TipoCombustible.GASOLINA, TipoCajaCambios.AUTOMATICO, 5, 5);
			Coche coche51 = new Coche("1022YZA", Marca.LAND_ROVER, "Evoque", 60, TipoCombustible.HIBRIDO, TipoCajaCambios.AUTOMATICO, 5, 5);
			Coche coche52 = new Coche("1122JKL", Marca.SEAT, "León", 22, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 5, 4);
			Coche coche53 = new Coche("3344MNO", Marca.SEAT, "Ateca", 28, TipoCombustible.HIBRIDO, TipoCajaCambios.AUTOMATICO, 5, 5);
			Coche coche54 = new Coche("5566PQR", Marca.SEAT, "Ibiza", 17, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 5, 3);
			Coche coche55 = new Coche("7788STU", Marca.TESLA, "Model 3", 35, TipoCombustible.ELECTRICO, TipoCajaCambios.AUTOMATICO, 5, 4);
			Coche coche56 = new Coche("9900VWX", Marca.TESLA, "Model S", 75, TipoCombustible.ELECTRICO, TipoCajaCambios.AUTOMATICO, 5, 4);
			Coche coche57 = new Coche("1022YZA", Marca.TESLA, "Model X", 85, TipoCombustible.ELECTRICO, TipoCajaCambios.AUTOMATICO, 7, 5);
			Coche coche58 = new Coche("1122JKL", Marca.PEUGEOT, "208", 15, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 5, 3);
			Coche coche59 = new Coche("3344MNO", Marca.PEUGEOT, "3008", 25, TipoCombustible.HIBRIDO, TipoCajaCambios.AUTOMATICO, 5, 5);
			Coche coche60 = new Coche("5566PQR", Marca.PEUGEOT, "508", 35, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 5, 4);
			Coche coche61 = new Coche("7788STU", Marca.RENAULT, "Clio", 16, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 5, 3);
			Coche coche62 = new Coche("9900VWX", Marca.RENAULT, "Megane", 20, TipoCombustible.HIBRIDO, TipoCajaCambios.AUTOMATICO, 5, 5);
			Coche coche63 = new Coche("1022YZA", Marca.RENAULT, "Koleos", 27, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 5, 5);
			Coche coche64 = new Coche("1122JKL", Marca.JEEP, "Wrangler", 45, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 5, 4);
			Coche coche65 = new Coche("3344MNO", Marca.JEEP, "Cherokee", 35, TipoCombustible.DIESEL, TipoCajaCambios.AUTOMATICO, 5, 5);
			Coche coche66 = new Coche("5566PQR", Marca.JEEP, "Grand Cherokee", 60, TipoCombustible.HIBRIDO, TipoCajaCambios.MANUAL, 5, 5);
			Coche coche67 = new Coche("7788STU", Marca.FIAT, "500", 15, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 4, 2);
			Coche coche68 = new Coche("9900VWX", Marca.FIAT, "Panda", 12, TipoCombustible.HIBRIDO, TipoCajaCambios.AUTOMATICO, 5, 4);
			Coche coche69 = new Coche("1022YZA", Marca.FIAT, "Tipo", 20, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 5, 4);
			Coche coche70 = new Coche("1122JKL", Marca.CITROEN, "C3", 14, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 5, 3);
			Coche coche71 = new Coche("3344MNO", Marca.CITROEN, "C4", 22, TipoCombustible.HIBRIDO, TipoCajaCambios.AUTOMATICO, 5, 4);
			Coche coche72 = new Coche("5566PQR", Marca.CITROEN, "C5 Aircross", 30, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 5, 5);
			Coche coche73 = new Coche("7788STU", Marca.OPEL, "Astra", 18, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 5, 4);
			Coche coche74 = new Coche("9900VWX", Marca.OPEL, "Grandland", 30, TipoCombustible.HIBRIDO, TipoCajaCambios.AUTOMATICO, 5, 5);
			Coche coche75 = new Coche("1022YZA", Marca.OPEL, "Mokka", 25, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 5, 5);
			
			dbManager.almacenarCoche(coche1);
			dbManager.almacenarCoche(coche2);
			dbManager.almacenarCoche(coche3);
			dbManager.almacenarCoche(coche4);
			dbManager.almacenarCoche(coche5);
			dbManager.almacenarCoche(coche6);
			dbManager.almacenarCoche(coche7);
			dbManager.almacenarCoche(coche8);
			dbManager.almacenarCoche(coche9);
			dbManager.almacenarCoche(coche10);
			dbManager.almacenarCoche(coche11);
			dbManager.almacenarCoche(coche12);
			dbManager.almacenarCoche(coche13);
			dbManager.almacenarCoche(coche14);
			dbManager.almacenarCoche(coche15);
			dbManager.almacenarCoche(coche16);
			dbManager.almacenarCoche(coche17);
			dbManager.almacenarCoche(coche18);
			dbManager.almacenarCoche(coche19);
			dbManager.almacenarCoche(coche20);
			dbManager.almacenarCoche(coche21);
			dbManager.almacenarCoche(coche22);
			dbManager.almacenarCoche(coche23);
			dbManager.almacenarCoche(coche24);
			dbManager.almacenarCoche(coche25);
			dbManager.almacenarCoche(coche26);
			dbManager.almacenarCoche(coche27);
			dbManager.almacenarCoche(coche28);
			dbManager.almacenarCoche(coche29);
			dbManager.almacenarCoche(coche30);
			dbManager.almacenarCoche(coche31);
			dbManager.almacenarCoche(coche32);
			dbManager.almacenarCoche(coche33);
			dbManager.almacenarCoche(coche34);
			dbManager.almacenarCoche(coche35);
			dbManager.almacenarCoche(coche36);
			dbManager.almacenarCoche(coche37);
			dbManager.almacenarCoche(coche38);
			dbManager.almacenarCoche(coche39);
			dbManager.almacenarCoche(coche40);
			dbManager.almacenarCoche(coche41);
			dbManager.almacenarCoche(coche42);
			dbManager.almacenarCoche(coche43);
			dbManager.almacenarCoche(coche44);
			dbManager.almacenarCoche(coche45);
			dbManager.almacenarCoche(coche46);
			dbManager.almacenarCoche(coche47);
			dbManager.almacenarCoche(coche48);
			dbManager.almacenarCoche(coche49);
			dbManager.almacenarCoche(coche50);
			dbManager.almacenarCoche(coche51);
			dbManager.almacenarCoche(coche52);
			dbManager.almacenarCoche(coche53);
			dbManager.almacenarCoche(coche54);
			dbManager.almacenarCoche(coche55);
			dbManager.almacenarCoche(coche56);
			dbManager.almacenarCoche(coche57);
			dbManager.almacenarCoche(coche58);
			dbManager.almacenarCoche(coche59);
			dbManager.almacenarCoche(coche60);
			dbManager.almacenarCoche(coche61);
			dbManager.almacenarCoche(coche62);
			dbManager.almacenarCoche(coche63);
			dbManager.almacenarCoche(coche64);
			dbManager.almacenarCoche(coche65);
			dbManager.almacenarCoche(coche66);
			dbManager.almacenarCoche(coche67);
			dbManager.almacenarCoche(coche68);
			dbManager.almacenarCoche(coche69);
			dbManager.almacenarCoche(coche70);
			dbManager.almacenarCoche(coche71);
			dbManager.almacenarCoche(coche72);
			dbManager.almacenarCoche(coche73);
			dbManager.almacenarCoche(coche74);
			dbManager.almacenarCoche(coche75);

			Moto moto1 = new Moto("1234YAMA", Marca.YAMAHA, "YZF-R1", 22, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 2, true, 998);
			Moto moto2 = new Moto("5678YAMA", Marca.YAMAHA, "MT-07", 8, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 2, false, 689);
			Moto moto3 = new Moto("9101YAMA", Marca.YAMAHA, "TMAX", 13, TipoCombustible.GASOLINA, TipoCajaCambios.AUTOMATICO, 2, true, 530);
			Moto moto4 = new Moto("1234KAWA", Marca.KAWASAKI, "Ninja ZX-10R", 16, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 2, false, 998);
			Moto moto5 = new Moto("5678KAWA", Marca.KAWASAKI, "Z900", 9.5f, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 2, false, 948);
			Moto moto6 = new Moto("9101KAWA", Marca.KAWASAKI, "Versys 650", 9, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 2, true, 649);
			Moto moto7 = new Moto("1234SUZU", Marca.SUZUKI, "GSX-R1000", 18, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 2, false, 999);
			Moto moto8 = new Moto("5678SUZU", Marca.SUZUKI, "V-Strom 650", 9.5f, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 2, true, 645);
			Moto moto9 = new Moto("9101SUZU", Marca.SUZUKI, "SV650", 7.5f, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 2, true, 645);
			Moto moto10 = new Moto("1234HARL", Marca.HARLEY_DAVIDSON, "Sportster S", 16, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 2, false, 1252);
			Moto moto11 = new Moto("5678HARL", Marca.HARLEY_DAVIDSON, "Iron 883", 9.5f, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 2, false, 883);
			Moto moto12 = new Moto("9101HARL", Marca.HARLEY_DAVIDSON, "Fat Boy", 21, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 2, false, 1745);
			Moto moto13 = new Moto("1234DUCA", Marca.DUCATI, "Panigale V4", 24, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 2, false, 1103);
			Moto moto14 = new Moto("5678DUCA", Marca.DUCATI, "Monster 821", 11.5f, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 2, false, 821);
			Moto moto15 = new Moto("9101DUCA", Marca.DUCATI, "Diavel 1260", 21.5f, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 2, true, 1262);
			Moto moto16 = new Moto("1234VESP", Marca.VESPA, "GTS 300", 6, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 2, true, 278);
			Moto moto17 = new Moto("5678VESP", Marca.VESPA, "Sprint 125", 4.5f, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 2, true, 124);
			Moto moto18 = new Moto("9101VESP", Marca.VESPA, "Primavera 50", 3.5f, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 2, false, 49);
			
			dbManager.almacenarMoto(moto1);
			dbManager.almacenarMoto(moto2);
			dbManager.almacenarMoto(moto3);
			dbManager.almacenarMoto(moto4);
			dbManager.almacenarMoto(moto5);
			dbManager.almacenarMoto(moto6);
			dbManager.almacenarMoto(moto7);
			dbManager.almacenarMoto(moto8);
			dbManager.almacenarMoto(moto9);
			dbManager.almacenarMoto(moto10);
			dbManager.almacenarMoto(moto11);
			dbManager.almacenarMoto(moto12);
			dbManager.almacenarMoto(moto13);
			dbManager.almacenarMoto(moto14);
			dbManager.almacenarMoto(moto15);
			dbManager.almacenarMoto(moto16);
			dbManager.almacenarMoto(moto17);
			dbManager.almacenarMoto(moto18);
			
			Furgoneta furgoneta1 = new Furgoneta("1234FORD", Marca.FORD, "Transit Custom", 25000, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 3, 1200, 1500);
			Furgoneta furgoneta2 = new Furgoneta("5678FORD", Marca.FORD, "Transit Connect", 22000, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 2, 800, 1000);
			Furgoneta furgoneta3 = new Furgoneta("9101FORD", Marca.FORD, "Transit 350", 28000, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 3, 1500, 2000);
			Furgoneta furgoneta4 = new Furgoneta("1234MERC", Marca.MERCEDES_BENZ, "Sprinter 314", 35000, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 3, 1500, 2000);
			Furgoneta furgoneta5 = new Furgoneta("5678MERC", Marca.MERCEDES_BENZ, "Vito 116", 28000, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 3, 1300, 1600);
			Furgoneta furgoneta6 = new Furgoneta("9101MERC", Marca.MERCEDES_BENZ, "V-Class", 45000, TipoCombustible.GASOLINA, TipoCajaCambios.AUTOMATICO, 8, 1200, 1400);
			Furgoneta furgoneta7 = new Furgoneta("1234VOLK", Marca.VOLKSWAGEN, "Transporter T6", 30000, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 3, 1300, 1700);
			Furgoneta furgoneta8 = new Furgoneta("5678VOLK", Marca.VOLKSWAGEN, "Crafter", 35000, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 3, 1500, 2000);
			Furgoneta furgoneta9 = new Furgoneta("9101VOLK", Marca.VOLKSWAGEN, "Caddy Maxi", 22000, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 2, 800, 1000);
			Furgoneta furgoneta10 = new Furgoneta("1234NISS", Marca.NISSAN, "NV300", 27000, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 3, 1200, 1500);
			Furgoneta furgoneta11 = new Furgoneta("5678NISS", Marca.NISSAN, "NV400", 32000, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 3, 1600, 2000);
			Furgoneta furgoneta12 = new Furgoneta("9101NISS", Marca.NISSAN, "NV200", 20000, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 2, 700, 800);
			Furgoneta furgoneta13 = new Furgoneta("1234PEUG", Marca.PEUGEOT, "Boxer", 28000, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 3, 1400, 1800);
			Furgoneta furgoneta14 = new Furgoneta("5678PEUG", Marca.PEUGEOT, "Partner", 24000, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 2, 800, 1000);
			Furgoneta furgoneta15 = new Furgoneta("9101PEUG", Marca.PEUGEOT, "Expert", 27000, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 3, 1200, 1500);
			Furgoneta furgoneta16 = new Furgoneta("1234RENU", Marca.RENAULT, "Master", 32000, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 3, 1500, 2000);
			Furgoneta furgoneta17 = new Furgoneta("5678RENU", Marca.RENAULT, "Trafic", 27000, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 3, 1200, 1500);
			Furgoneta furgoneta18 = new Furgoneta("9101RENU", Marca.RENAULT, "Kangoo", 22000, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 2, 700, 800);
			Furgoneta furgoneta19 = new Furgoneta("1234FIAT", Marca.FIAT, "Ducato", 29000, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 3, 1400, 1800);
			Furgoneta furgoneta20 = new Furgoneta("5678FIAT", Marca.FIAT, "Fiorino", 21000, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 2, 600, 700);
			Furgoneta furgoneta21 = new Furgoneta("9101FIAT", Marca.FIAT, "Talento", 27000, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 3, 1200, 1500);
			Furgoneta furgoneta22 = new Furgoneta("1234CITR", Marca.CITROEN, "Jumper", 30000, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 3, 1400, 1800);
			Furgoneta furgoneta23 = new Furgoneta("5678CITR", Marca.CITROEN, "Berlingo", 22000, TipoCombustible.GASOLINA, TipoCajaCambios.MANUAL, 2, 700, 800);
			Furgoneta furgoneta24 = new Furgoneta("9101CITR", Marca.CITROEN, "SpaceTourer", 35000, TipoCombustible.DIESEL, TipoCajaCambios.MANUAL, 7, 1200, 1400);

			dbManager.almacenarFurgoneta(furgoneta1);
			dbManager.almacenarFurgoneta(furgoneta2);
			dbManager.almacenarFurgoneta(furgoneta3);
			dbManager.almacenarFurgoneta(furgoneta4);
			dbManager.almacenarFurgoneta(furgoneta5);
			dbManager.almacenarFurgoneta(furgoneta6);
			dbManager.almacenarFurgoneta(furgoneta7);
			dbManager.almacenarFurgoneta(furgoneta8);
			dbManager.almacenarFurgoneta(furgoneta9);
			dbManager.almacenarFurgoneta(furgoneta10);
			dbManager.almacenarFurgoneta(furgoneta11);
			dbManager.almacenarFurgoneta(furgoneta12);
			dbManager.almacenarFurgoneta(furgoneta13);
			dbManager.almacenarFurgoneta(furgoneta14);
			dbManager.almacenarFurgoneta(furgoneta15);
			dbManager.almacenarFurgoneta(furgoneta16);
			dbManager.almacenarFurgoneta(furgoneta17);
			dbManager.almacenarFurgoneta(furgoneta18);
			dbManager.almacenarFurgoneta(furgoneta19);
			dbManager.almacenarFurgoneta(furgoneta20);
			dbManager.almacenarFurgoneta(furgoneta21);
			dbManager.almacenarFurgoneta(furgoneta22);
			dbManager.almacenarFurgoneta(furgoneta23);
			dbManager.almacenarFurgoneta(furgoneta24);
			
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

}
